# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Avery's Blog
tagline:             'A bunch of random stuff'
description:         'This is the place where I write a bunch of stuff about things.'
url:                 http://blog.averymiller.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Avery Miller
  url:               http://averymiller.org
  email:             avery@averymiller.org

# Custom vars
version:             1.0.0
